# Generated by Django 3.1 on 2020-08-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='elo_rating',
            field=models.FloatField(default=1000.0),
        ),
    ]
