# Generated by Django 3.1 on 2020-08-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_flag_elo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted',
            field=models.BooleanField(db_index=True),
        ),
    ]
