# Generated by Django 3.1 on 2020-08-28 02:41
import trueskill
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0003_add_index_to_voted"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="trueskill_rating_mu",
            field=models.FloatField(default=trueskill.Rating().mu),
        ),
        migrations.AddField(
            model_name="flag",
            name="trueskill_rating_sigma",
            field=models.FloatField(default=trueskill.Rating().sigma),
        ),
    ]
