# Generated by Django 3.1 on 2020-09-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0006_split_vote_ip"),
    ]

    operations = [
        migrations.RemoveField(model_name="vote", name="voted",),
    ]
