# Generated by Django 3.1 on 2020-09-12 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0007_remove_vote_voted"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
