# Generated by Django 3.1 on 2020-09-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0008_flag_created_updated_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="include_in_votes",
            field=models.BooleanField(default=True),
        ),
    ]
